version: '3'

services:
  web:
    image: nginx
    container_name: web
    ports:
      - 8080:80
    volumes:
      - ../app:/var/www/app
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./php
    image: php-dev
    container_name: php
    volumes:
      - ../app:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: app_root_pass
      MYSQL_DATABASE: app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf

  cache:
    image: redis
    container_name: cache

volumes:
  db-store:
    driver: local
