version: "3"

services:
  web:
    image: nginx
    container_name: web
    ports:
      - 8080:80
    volumes:
      - ../app:/var/www/app
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: ./php
    image: php-dev
    container_name: app
    volumes:
      - ../app:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: app
      TZ: "Asia/Tokyo"
    ports:
      - 33306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d

  cache:
    image: redis
    container_name: cache
